# Data Cleaning and Methodology
## Predicting Road Accident Severity Using Data Science

**Team Role:** Member 3 — Data Cleaning, Preprocessing, and Methodology

**Dataset:** UK Road Safety Collisions, 2024–2025

**Objective:** Inspect the dataset, identify missing values and duplicate records, check data types and invalid values, document preprocessing decisions, and export a cleaned dataset for subsequent analysis.

**Tools:** Python, Pandas, and NumPy in Google Colab.

In [ ]:

# Cell 1: Load the dataset

import pandas as pd
import numpy as np

DATA_FILE = "/content/collisions_2024_2025_prepared.csv.gz"

df = pd.read_csv(DATA_FILE, low_memory=False)

clean_df = df.copy()

print("Dataset loaded successfully!")
print("Rows:", clean_df.shape[0])
print("Columns:", clean_df.shape[1])

display(clean_df.head())

Dataset loaded successfully!
Rows: 202452
Columns: 68

,collision_index,collision_year,longitude,latitude,police_force,collision_severity,number_of_vehicles,number_of_casualties,date,day_of_week,...,time_band,rush_hour,light_group,darkness_lighting,weather_group,high_winds,surface_group,junction_group,road_class_group,area
0,202417H100324,2024,-1.22869,54.65155,17,2,1,5,12/01/2024,6,...,Evening,0,Darkness,Dark - lit,Fine,0.0,Wet or damp,Not at junction,A road,Rural
1,202417M110024,2024,-1.22715,54.56618,17,3,2,1,01/07/2024,2,...,Evening,0,Darkness,Dark - lit,Fine,0.0,Wet or damp,Not at junction,Unclassified,Urban
2,2024480537342,2024,-0.10449,51.50852,48,3,1,2,18/09/2024,4,...,Afternoon,1,Daylight,Daylight,Fine,0.0,Dry,At junction,A road,Urban
3,202417M105824,2024,-1.22319,54.56529,17,3,2,2,04/05/2024,7,...,Afternoon,0,Daylight,Daylight,Fine,0.0,Dry,At junction,Unclassified,Urban
4,202417M114324,2024,-1.21662,54.57314,17,3,1,1,30/08/2024,6,...,Evening,0,Darkness,Dark - lit,Fine,0.0,Dry,At junction,A road,Rural

In [ ]:

# Cell 2: Check missing values

missing_values = clean_df.isnull().sum()

print("Missing values in each column:")
display(missing_values[missing_values > 0].sort_values(ascending=False))

Missing values in each column:

carriageway_hazards_label        194021
junction_detail_label             15135
junction_detail                   15135
junction_group                    15135
trunk_road_flag                   14188
trunk_road_flag_label             14188
pedestrian_crossing_label         10874
pedestrian_crossing               10874
carriageway_hazards                9124
junction_control_label             7710
junction_control                   7710
high_winds                         5530
weather_group                      5530
weather_conditions_label           5530
weather_conditions                 5530
road_type                          4521
road_type_label                    4521
surface_group                      4350
road_surface_conditions            4350
road_surface_conditions_label      4350
second_road_class                   321
second_road_class_label             321
light_group                          22
light_conditions                     22
darkness_lighting                    22
light_conditions_label               22
area                                  7
urban_or_rural_area_label             7
urban_or_rural_area                   7
first_road_class_label                6
first_road_class                      6
road_class_group                      6
speed_limit_label                     3
speed_limit                           3
longitude                             2
latitude                              2
dtype: int64

In [ ]:

# Cell 3: Check and Remove Exact Duplicates

before = len(clean_df)

clean_df = clean_df.drop_duplicates().copy()

removed = before - len(clean_df)

print("Duplicate rows removed:", removed)
print("Rows remaining:", len(clean_df))
print("Columns remaining:", len(clean_df.columns))

Duplicate rows removed: 0
Rows remaining: 202452
Columns remaining: 68

In [ ]:

# Cell 4: Validate Years and Accident Severity

print("Records per year:")
display(clean_df["collision_year"].value_counts().sort_index())

print("\nAccident severity distribution:")
display(clean_df["collision_severity"].value_counts(dropna=False).sort_index())

print("\nMissing target values:", clean_df["collision_severity"].isna().sum())

Records per year:

collision_year
2024    100927
2025    101525
Name: count, dtype: int64

Accident severity distribution:

collision_severity
1      2955
2     48758
3    150739
Name: count, dtype: int64

Missing target values: 0

In [ ]:
# Cell 5: Review Missing Values and Data Types

missing_summary = pd.DataFrame({
    "Missing Count": clean_df.isnull().sum(),
    "Missing Percentage": (
        clean_df.isnull().mean() * 100
    ).round(2),
    "Data Type": clean_df.dtypes.astype(str)
})

missing_summary = missing_summary[
    missing_summary["Missing Count"] > 0
].sort_values("Missing Percentage", ascending=False)

print("Columns with missing values:", len(missing_summary))
display(missing_summary)

Columns with missing values: 36

                               Missing Count  Missing Percentage Data Type
carriageway_hazards_label             194021               95.84    object
junction_detail_label                  15135                7.48    object
junction_detail                        15135                7.48   float64
junction_group                         15135                7.48    object
trunk_road_flag                        14188                7.01   float64
trunk_road_flag_label                  14188                7.01    object
pedestrian_crossing_label              10874                5.37    object
pedestrian_crossing                    10874                5.37   float64
carriageway_hazards                     9124                4.51   float64
junction_control_label                  7710                3.81    object
junction_control                        7710                3.81   float64
high_winds                              5530                2.73   float64
weather_group                           5530                2.73    object
weather_conditions_label                5530                2.73    object
weather_conditions                      5530                2.73   float64
road_type                               4521                2.23   float64
road_type_label                         4521                2.23    object
surface_group                           4350                2.15    object
road_surface_conditions                 4350                2.15   float64
road_surface_conditions_label           4350                2.15    object
second_road_class                        321                0.16   float64
second_road_class_label                  321                0.16    object
light_group                               22                0.01    object
light_conditions                          22                0.01   float64
darkness_lighting                         22                0.01    object
light_conditions_label                    22                0.01    object
longitude                                  2                0.00   float64
latitude                                   2                0.00   float64
first_road_class                           6                0.00   float64
first_road_class_label                     6                0.00    object
urban_or_rural_area                        7                0.00   float64
speed_limit                                3                0.00   float64
speed_limit_label                          3                0.00    object
urban_or_rural_area_label                  7                0.00    object
road_class_group                           6                0.00    object
area                                       7                0.00    object

In [ ]:
# Cell 6: Inspect Related Columns

columns_to_check = [
    "carriageway_hazards",
    "carriageway_hazards_label",
    "junction_detail",
    "junction_detail_label",
    "junction_group",
    "weather_conditions",
    "weather_conditions_label",
    "weather_group",
    "road_surface_conditions",
    "road_surface_conditions_label",
    "surface_group"
]

for column in columns_to_check:
    if column in clean_df.columns:
        print(f"\n--- {column} ---")
        print("Missing values:", clean_df[column].isnull().sum())
        print("Unique values:", clean_df[column].nunique(dropna=True))
        display(clean_df[column].value_counts(dropna=False).head(8))

--- carriageway_hazards ---
Missing values: 9124
Unique values: 12

carriageway_hazards
0.0     184897
NaN       9124
13.0      2238
17.0      1824
21.0       837
15.0       623
11.0       587
20.0       536
Name: count, dtype: int64

--- carriageway_hazards_label ---
Missing values: 194021
Unique values: 11

carriageway_hazards_label
NaN                                                                       194021
Roadworks                                                                   2238
Other object in carriageway                                                 1824
Poor or defective road surface                                               837
Mud                                                                          623
Defective traffic signals                                                    587
Any animal in carriageway (except ridden horse)                              536
Permanent road signing or markings defective or obscured or inadequate       452
Name: count, dtype: int64

--- junction_detail ---
Missing values: 15135
Unique values: 6

junction_detail
0.0     91472
13.0    56202
16.0    18951
NaN     15135
19.0    13119
18.0     4400
17.0     3173
Name: count, dtype: int64

--- junction_detail_label ---
Missing values: 15135
Unique values: 6

junction_detail_label
Not at junction or within 20 metres                   91472
T or staggered junction                               56202
Crossroads                                            18951
NaN                                                   15135
Other junction                                        13119
Using private drive or entrance                        4400
Junction with more than four arms (not roundabout)     3173
Name: count, dtype: int64

--- junction_group ---
Missing values: 15135
Unique values: 2

junction_group
At junction        95845
Not at junction    91472
NaN                15135
Name: count, dtype: int64

--- weather_conditions ---
Missing values: 5530
Unique values: 8

weather_conditions
1.0    163006
2.0     22558
8.0      6366
NaN      5530
5.0      2005
4.0      1650
7.0       816
3.0       477
Name: count, dtype: int64

--- weather_conditions_label ---
Missing values: 5530
Unique values: 8

weather_conditions_label
Fine no high winds       163006
Raining no high winds     22558
Other                      6366
NaN                        5530
Raining + high winds       2005
Fine + high winds          1650
Fog or mist                 816
Snowing no high winds       477
Name: count, dtype: int64

--- weather_group ---
Missing values: 5530
Unique values: 5

weather_group
Fine           164656
Rain            24563
Other            6366
NaN              5530
Fog or mist       816
Snow              521
Name: count, dtype: int64

--- road_surface_conditions ---
Missing values: 4350
Unique values: 5

road_surface_conditions
1.0    147511
2.0     47667
NaN      4350
4.0      2276
5.0       343
3.0       305
Name: count, dtype: int64

--- road_surface_conditions_label ---
Missing values: 4350
Unique values: 5

road_surface_conditions_label
Dry                     147511
Wet or damp              47667
NaN                       4350
Frost or ice              2276
Flood over 3cm. deep       343
Snow                       305
Name: count, dtype: int64

--- surface_group ---
Missing values: 4350
Unique values: 4

surface_group
Dry             147511
Wet or damp      47667
NaN               4350
Snow or ice       2581
Other hazard       343
Name: count, dtype: int64

In [ ]:
# Cell 7: Verify Carriageway Hazard Labels

print("Hazard code and label comparison:")

hazard_check = clean_df[
    ["carriageway_hazards", "carriageway_hazards_label"]
].copy()

print("\nMissing values in each column:")
display(hazard_check.isnull().sum())

print("\nRows where the code exists but the label is missing:")
display(
    hazard_check[
        hazard_check["carriageway_hazards"].notna()
        & hazard_check["carriageway_hazards_label"].isna()
    ].head(10)
)

print("\nRows where both values exist:")
display(
    hazard_check[
        hazard_check["carriageway_hazards"].notna()
        & hazard_check["carriageway_hazards_label"].notna()
    ].head(10)
)

Hazard code and label comparison:

Missing values in each column:

carriageway_hazards            9124
carriageway_hazards_label    194021
dtype: int64

Rows where the code exists but the label is missing:

   carriageway_hazards carriageway_hazards_label
0                  0.0                       NaN
1                  0.0                       NaN
2                  0.0                       NaN
3                  0.0                       NaN
4                  0.0                       NaN
5                  0.0                       NaN
6                  0.0                       NaN
7                  0.0                       NaN
8                  0.0                       NaN
9                  0.0                       NaN

Rows where both values exist:

     carriageway_hazards                carriageway_hazards_label
38                  13.0                                Roadworks
104                 13.0                                Roadworks
357                 17.0              Other object in carriageway
447                 19.0  Pedestrian in carriageway - not injured
630                 13.0                                Roadworks
642                 17.0              Other object in carriageway
694                 19.0  Pedestrian in carriageway - not injured
708                 19.0  Pedestrian in carriageway - not injured
711                 13.0                                Roadworks
723                 17.0              Other object in carriageway

In [ ]:
# Cell 8: Check Missing Hazard Labels by Code

hazard_summary = (
    clean_df.groupby("carriageway_hazards", dropna=False)
    .agg(
        Total_Rows=("carriageway_hazards_label", "size"),
        Missing_Labels=("carriageway_hazards_label", lambda x: x.isna().sum()),
        Available_Labels=("carriageway_hazards_label", lambda x: x.notna().sum())
    )
)

hazard_summary["Missing_Label_Percentage"] = (
    hazard_summary["Missing_Labels"] / hazard_summary["Total_Rows"] * 100
).round(2)

display(hazard_summary.sort_index())

,Total_Rows,Missing_Labels,Available_Labels,Missing_Label_Percentage
carriageway_hazards,,,,
0.0,184897,184897,0,100.0
11.0,587,0,587,0.0
12.0,452,0,452,0.0
13.0,2238,0,2238,0.0
14.0,247,0,247,0.0
15.0,623,0,623,0.0
16.0,322,0,322,0.0
17.0,1824,0,1824,0.0
18.0,355,0,355,0.0
19.0,410,0,410,0.0
20.0,536,0,536,0.0
21.0,837,0,837,0.0
NaN,9124,9124,0,100.0

In [ ]:
# Cell 9: Create a Safe Working Copy

# Keep the original dataset unchanged
original_df = df.copy()

# Create the working dataset for cleaning
clean_df = original_df.copy()

# Remove exact duplicate rows
rows_before = len(clean_df)
clean_df = clean_df.drop_duplicates().copy()
duplicates_removed = rows_before - len(clean_df)

print("Original dataset rows:", len(original_df))
print("Rows after duplicate removal:", len(clean_df))
print("Duplicate rows removed:", duplicates_removed)
print("Columns:", len(clean_df.columns))
print("Missing target values:", clean_df["collision_severity"].isna().sum())

Original dataset rows: 202452
Rows after duplicate removal: 202452
Duplicate rows removed: 0
Columns: 68
Missing target values: 0

In [ ]:
# Cell 10: Validate Data Types and Values

# Check the data types of all columns
print("Data types:")
display(clean_df.dtypes.value_counts().rename("Number of Columns"))

# Check the target variable
print("\nAccident severity values:")
display(clean_df["collision_severity"].value_counts().sort_index())

# Check the dataset years
print("\nCollision years:")
display(clean_df["collision_year"].value_counts().sort_index())

# Check invalid geographic coordinates
invalid_latitude = (
    (clean_df["latitude"] < -90) |
    (clean_df["latitude"] > 90)
).sum()

invalid_longitude = (
    (clean_df["longitude"] < -180) |
    (clean_df["longitude"] > 180)
).sum()

print("\nInvalid latitude values:", invalid_latitude)
print("Invalid longitude values:", invalid_longitude)

# Check invalid speed limits
print(
    "\nZero or negative speed limits:",
    (clean_df["speed_limit"] <= 0).sum()
)

# Check unexpected target categories
unexpected_severity = clean_df.loc[
    ~clean_df["collision_severity"].isin([1, 2, 3]),
    "collision_severity"
]

print("\nUnexpected severity values:")
display(unexpected_severity.value_counts(dropna=False))

Data types:

object     36
float64    19
int64      13
Name: Number of Columns, dtype: int64

Accident severity values:

collision_severity
1      2955
2     48758
3    150739
Name: count, dtype: int64

Collision years:

collision_year
2024    100927
2025    101525
Name: count, dtype: int64

Invalid latitude values: 0
Invalid longitude values: 0

Zero or negative speed limits: 0

Unexpected severity values:

Series([], Name: count, dtype: int64)

In [ ]:
# Cell 11: Identify Label Columns

label_columns = [
    column for column in clean_df.columns
    if column.endswith("_label")
]

print("Number of label columns:", len(label_columns))
print("\nLabel columns:")
for column in label_columns:
    print(column)

print("\nTarget column preserved:",
      "collision_severity" in clean_df.columns)

Number of label columns: 18

Label columns:
collision_severity_label
day_of_week_label
police_force_label
first_road_class_label
road_type_label
speed_limit_label
junction_detail_label
junction_control_label
second_road_class_label
pedestrian_crossing_label
light_conditions_label
weather_conditions_label
road_surface_conditions_label
carriageway_hazards_label
urban_or_rural_area_label
did_police_officer_attend_scene_of_accident_label
trunk_road_flag_label
collision_injury_based_label

Target column preserved: True

In [ ]:
# Cell 12: Remove Unreliable and Redundant Label Columns

# Keep original coded columns for analysis
columns_to_remove = [
    "collision_severity_label",
    "day_of_week_label",
    "police_force_label",
    "first_road_class_label",
    "road_type_label",
    "speed_limit_label",
    "junction_detail_label",
    "junction_control_label",
    "second_road_class_label",
    "pedestrian_crossing_label",
    "light_conditions_label",
    "weather_conditions_label",
    "road_surface_conditions_label",
    "carriageway_hazards_label",
    "urban_or_rural_area_label",
    "did_police_officer_attend_scene_of_accident_label",
    "trunk_road_flag_label",
    "collision_injury_based_label"
]

# Remove only columns that exist
columns_to_remove = [
    column for column in columns_to_remove
    if column in clean_df.columns
]

clean_df = clean_df.drop(columns=columns_to_remove).copy()

print("Label columns removed:", len(columns_to_remove))
print("Rows remaining:", len(clean_df))
print("Columns remaining:", len(clean_df.columns))
print("Target preserved:", "collision_severity" in clean_df.columns)

Label columns removed: 18
Rows remaining: 202452
Columns remaining: 50
Target preserved: True

In [ ]:
# Cell 13: Handle Missing Values in Categorical Numeric Columns

# Numeric-coded categorical columns
categorical_numeric_columns = [
    "police_force",
    "first_road_class",
    "road_type",
    "speed_limit",
    "junction_detail",
    "junction_control",
    "second_road_class",
    "pedestrian_crossing",
    "light_conditions",
    "weather_conditions",
    "road_surface_conditions",
    "carriageway_hazards",
    "urban_or_rural_area",
    "did_police_officer_attend_scene_of_accident",
    "trunk_road_flag"
]

# Process only columns that exist and contain missing values
for column in categorical_numeric_columns:
    if column in clean_df.columns and clean_df[column].isna().any():
        clean_df[column] = clean_df[column].fillna(-1)

print("Missing values handled in numeric-coded categorical columns.")

remaining_missing = clean_df.isna().sum()
display(
    remaining_missing[remaining_missing > 0]
    .sort_values(ascending=False)
)

print("\nRows remaining:", len(clean_df))
print("Columns remaining:", len(clean_df.columns))

Missing values handled in numeric-coded categorical columns.

junction_group       15135
high_winds            5530
weather_group         5530
surface_group         4350
light_group             22
darkness_lighting       22
area                     7
road_class_group         6
latitude                 2
longitude                2
dtype: int64

Rows remaining: 202452
Columns remaining: 50

In [ ]:
# Cell 14: Handle Missing Values in Categorical Text Columns

text_categorical_columns = [
    "junction_group",
    "weather_group",
    "surface_group",
    "light_group",
    "darkness_lighting",
    "area",
    "road_class_group"
]

for column in text_categorical_columns:
    if column in clean_df.columns:
        clean_df[column] = clean_df[column].fillna("Unknown")

print("Missing values handled in categorical text columns.")

print("\nRemaining missing values:")
remaining_missing = clean_df.isna().sum()
display(remaining_missing[remaining_missing > 0])

print("\nRows remaining:", len(clean_df))
print("Columns remaining:", len(clean_df.columns))

Missing values handled in categorical text columns.

Remaining missing values:

longitude        2
latitude         2
high_winds    5530
dtype: int64

Rows remaining: 202452
Columns remaining: 50

In [ ]:
# Cell 15: Handle Remaining Missing Values

# Keep all accident records.
# Missing coordinates remain missing because we cannot infer their locations.
# Use a separate indicator for unknown high-wind information.
clean_df["high_winds_unknown"] = clean_df["high_winds"].isna().astype(int)

print("Unknown high_winds records:",
      clean_df["high_winds_unknown"].sum())

print("Missing latitude:", clean_df["latitude"].isna().sum())
print("Missing longitude:", clean_df["longitude"].isna().sum())

print("Rows preserved:", len(clean_df))
print("Columns:", len(clean_df.columns))

Unknown high_winds records: 5530
Missing latitude: 2
Missing longitude: 2
Rows preserved: 202452
Columns: 51

In [ ]:
# Cell 16: Validate the Cleaned Dataset

print("FINAL DATASET VALIDATION")
print("-" * 35)

print("Rows:", len(clean_df))
print("Columns:", len(clean_df.columns))
print("Duplicate rows:", clean_df.duplicated().sum())

print("\nMissing values by column:")
remaining = clean_df.isna().sum()
display(remaining[remaining > 0])

print("\nTarget validation:")
print("Missing target values:",
      clean_df["collision_severity"].isna().sum())
print("Target distribution:")
display(clean_df["collision_severity"].value_counts().sort_index())

print("\nYear validation:")
display(clean_df["collision_year"].value_counts().sort_index())

print("\nHigh-wind unknown indicator:")
display(clean_df["high_winds_unknown"].value_counts().sort_index())

FINAL DATASET VALIDATION
-----------------------------------
Rows: 202452
Columns: 51
Duplicate rows: 0

Missing values by column:

longitude        2
latitude         2
high_winds    5530
dtype: int64

Target validation:
Missing target values: 0
Target distribution:

collision_severity
1      2955
2     48758
3    150739
Name: count, dtype: int64

Year validation:

collision_year
2024    100927
2025    101525
Name: count, dtype: int64

High-wind unknown indicator:

high_winds_unknown
0    196922
1      5530
Name: count, dtype: int64

In [ ]:
# Cell 17: Check Potential Invalid Values

print("=== DATA QUALITY CHECK ===")

# Check numerical ranges
print("\n1. Latitude outside valid range:")
print(((clean_df["latitude"] < -90) |
       (clean_df["latitude"] > 90)).sum())

print("\n2. Longitude outside valid range:")
print(((clean_df["longitude"] < -180) |
       (clean_df["longitude"] > 180)).sum())

print("\n3. Zero or negative speed limits:")
print((clean_df["speed_limit"] <= 0).sum())

# Check target values
print("\n4. Collision severity values:")
print(clean_df["collision_severity"].value_counts(dropna=False).sort_index())

# Check categorical codes
columns_to_check = [
    "road_type",
    "junction_detail",
    "junction_control",
    "light_conditions",
    "weather_conditions",
    "road_surface_conditions",
    "pedestrian_crossing",
    "carriageway_hazards"
]

print("\n5. Unique values in categorical columns:")
for col in columns_to_check:
    if col in clean_df.columns:
        print(f"\n{col}:")
        print(sorted(clean_df[col].dropna().unique().tolist()))

=== DATA QUALITY CHECK ===

1. Latitude outside valid range:
0

2. Longitude outside valid range:
0

3. Zero or negative speed limits:
3

4. Collision severity values:
collision_severity
1      2955
2     48758
3    150739
Name: count, dtype: int64

5. Unique values in categorical columns:

road_type:
[-1.0, 1.0, 2.0, 3.0, 6.0, 7.0]

junction_detail:
[-1.0, 0.0, 13.0, 16.0, 17.0, 18.0, 19.0]

junction_control:
[-1.0, 0.0, 1.0, 2.0, 3.0, 4.0]

light_conditions:
[-1.0, 1.0, 4.0, 5.0, 6.0, 7.0]

weather_conditions:
[-1.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]

road_surface_conditions:
[-1.0, 1.0, 2.0, 3.0, 4.0, 5.0]

pedestrian_crossing:
[-1.0, 0.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0]

carriageway_hazards:
[-1.0, 0.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0]

In [ ]:
# Cell 17: Inspect Invalid Speed Limits

invalid_speed = clean_df[
    clean_df["speed_limit"].isna() |
    (clean_df["speed_limit"] <= 0)
]

print("Records with invalid speed limits:", len(invalid_speed))

display(invalid_speed[
    ["collision_year", "speed_limit", "road_type",
     "urban_or_rural_area", "collision_severity"]
])

Records with invalid speed limits: 3

,collision_year,speed_limit,road_type,urban_or_rural_area,collision_severity
55125,2024,-1.0,6.0,1.0,2
63151,2024,-1.0,6.0,1.0,3
70755,2024,-1.0,-1.0,1.0,3

In [ ]:
# Cell 19: Verify Missing Speed Limit Values

print("Speed limit values in the original dataset:")
display(df["speed_limit"].value_counts(dropna=False).sort_index())

print("\nSpeed limit values in the cleaned dataset:")
display(clean_df["speed_limit"].value_counts(dropna=False).sort_index())

print("\nRows with speed_limit = -1:")
display(
    clean_df.loc[
        clean_df["speed_limit"] == -1,
        ["collision_year", "speed_limit", "road_type",
         "urban_or_rural_area", "collision_severity"]
    ]
)

Speed limit values in the original dataset:

speed_limit
20.0    38926
30.0    99930
40.0    17835
50.0     9290
60.0    25418
70.0    11050
NaN         3
Name: count, dtype: int64

Speed limit values in the cleaned dataset:

speed_limit
-1.0         3
 20.0    38926
 30.0    99930
 40.0    17835
 50.0     9290
 60.0    25418
 70.0    11050
Name: count, dtype: int64

Rows with speed_limit = -1:

,collision_year,speed_limit,road_type,urban_or_rural_area,collision_severity
55125,2024,-1.0,6.0,1.0,2
63151,2024,-1.0,6.0,1.0,3
70755,2024,-1.0,-1.0,1.0,3

In [ ]:
# Cell 20: Inspect Date and Time Columns

date_columns = [
    col for col in clean_df.columns
    if "date" in col.lower() or "time" in col.lower()
]

print("Date and time columns:", date_columns)

for col in date_columns:
    print(f"\n--- {col} ---")
    print("Data type:", clean_df[col].dtype)
    print("Missing values:", clean_df[col].isna().sum())
    display(clean_df[col].head())

Date and time columns: ['date', 'time', 'datetime', 'time_band']

--- date ---
Data type: object
Missing values: 0

0    12/01/2024
1    01/07/2024
2    18/09/2024
3    04/05/2024
4    30/08/2024
Name: date, dtype: object

--- time ---
Data type: object
Missing values: 0

0    19:30
1    22:15
2    17:00
3    16:10
4    20:16
Name: time, dtype: object

--- datetime ---
Data type: object
Missing values: 0

0    2024-01-12 19:30:00
1    2024-07-01 22:15:00
2    2024-09-18 17:00:00
3    2024-05-04 16:10:00
4    2024-08-30 20:16:00
Name: datetime, dtype: object

--- time_band ---
Data type: object
Missing values: 0

0      Evening
1      Evening
2    Afternoon
3    Afternoon
4      Evening
Name: time_band, dtype: object

In [ ]:
# Cell 21: Convert Date and Datetime Columns

# Convert date to datetime format
clean_df["date"] = pd.to_datetime(
    clean_df["date"],
    format="%d/%m/%Y",
    errors="coerce"
)

# Convert datetime to datetime format
clean_df["datetime"] = pd.to_datetime(
    clean_df["datetime"],
    errors="coerce"
)

print("Date dtype:", clean_df["date"].dtype)
print("Datetime dtype:", clean_df["datetime"].dtype)

print("\nMissing dates after conversion:")
print(clean_df["date"].isna().sum())

print("\nMissing datetimes after conversion:")
print(clean_df["datetime"].isna().sum())

display(clean_df[["date", "time", "datetime", "time_band"]].head())

Date dtype: datetime64[ns]
Datetime dtype: datetime64[ns]

Missing dates after conversion:
0

Missing datetimes after conversion:
0

        date   time            datetime  time_band
0 2024-01-12  19:30 2024-01-12 19:30:00    Evening
1 2024-07-01  22:15 2024-07-01 22:15:00    Evening
2 2024-09-18  17:00 2024-09-18 17:00:00  Afternoon
3 2024-05-04  16:10 2024-05-04 16:10:00  Afternoon
4 2024-08-30  20:16 2024-08-30 20:16:00    Evening

In [ ]:
# Cell 22: Validate Date and Time Consistency

# Reconstruct datetime from date and time
combined_datetime = pd.to_datetime(
    clean_df["date"].dt.strftime("%Y-%m-%d") + " " +
    clean_df["time"].astype(str),
    errors="coerce"
)

# Compare with the existing datetime column
mismatch = (
    combined_datetime.notna() &
    clean_df["datetime"].ne(combined_datetime)
)

print("Unparseable date/time values:",
      combined_datetime.isna().sum())

print("Datetime mismatches:", mismatch.sum())

if mismatch.any():
    display(clean_df.loc[
        mismatch,
        ["date", "time", "datetime"]
    ].head(10))
else:
    print("Date, time, and datetime are consistent.")

Unparseable date/time values: 0
Datetime mismatches: 0
Date, time, and datetime are consistent.

In [ ]:
# Cell 23: Final Missing Values Review

missing_summary = pd.DataFrame({
    "Missing_Count": clean_df.isna().sum(),
    "Missing_Percentage": (
        clean_df.isna().mean() * 100
    ).round(2)
})

missing_summary = missing_summary[
    missing_summary["Missing_Count"] > 0
].sort_values("Missing_Count", ascending=False)

print("Remaining Missing Values:")
display(missing_summary)

print("\nDataset shape:", clean_df.shape)
print("Duplicate rows:", clean_df.duplicated().sum())

Remaining Missing Values:

            Missing_Count  Missing_Percentage
high_winds           5530                2.73
longitude               2                0.00
latitude                2                0.00

Dataset shape: (202452, 51)
Duplicate rows: 0

In [ ]:
# Cell 24: Add Missing-Value Indicators

# Identify records with missing coordinates
clean_df["coordinates_unknown"] = (
    clean_df["latitude"].isna() |
    clean_df["longitude"].isna()
).astype(int)

# Keep original missing values; do not invent coordinates
print("Missing high_winds:", clean_df["high_winds"].isna().sum())
print("Missing latitude:", clean_df["latitude"].isna().sum())
print("Missing longitude:", clean_df["longitude"].isna().sum())

print("\nMissing-coordinate indicator:")
display(clean_df["coordinates_unknown"].value_counts().sort_index())

print("\nDataset shape:", clean_df.shape)

Missing high_winds: 5530
Missing latitude: 2
Missing longitude: 2

Missing-coordinate indicator:

coordinates_unknown
0    202450
1         2
Name: count, dtype: int64

Dataset shape: (202452, 52)

In [ ]:

# Cell 25: Export Cleaned Dataset

OUTPUT_FILE = "/content/UK_Road_Accidents_Cleaned_2024_2025.csv"

clean_df.to_csv(OUTPUT_FILE, index=False)

# Verify the exported file
check_df = pd.read_csv(OUTPUT_FILE, low_memory=False)

print("Export successful!")
print("Original cleaned shape:", clean_df.shape)
print("Exported shape:", check_df.shape)
print("Duplicate rows:", check_df.duplicated().sum())
print("Target missing values:", check_df["collision_severity"].isna().sum())
print("File path:", OUTPUT_FILE)

Export successful!
Original cleaned shape: (202452, 52)
Exported shape: (202452, 52)
Duplicate rows: 0
Target missing values: 0
File path: /content/UK_Road_Accidents_Cleaned_2024_2025.csv

In [ ]:
from google.colab import files
files.download("/content/UK_Road_Accidents_Cleaned_2024_2025.csv")